### ISSUE TITLE
You both are stupid

### ISSUE THREAD

**Issue by amitdahan** [cuzi/CppCatchDaFlagMTA#1]
Need a fix ASAP

**Comment by cuzi** [comment]
issue resolved 
string tmpTitle = amit.getTitle();
amit.setTitle(tomer.getTitle());
tomer.setTitle(tmpTitle);

cout << amit.getTitle() << endl;     // stupid
cout << tomer.getTitle() << endl;  // smartass
cout << ben.getTitle() << endl;     // stupid
